"""empty message

Revision ID: 70c860ca7756
Revises: aed7deaca688
Create Date: 2018-11-30 00:44:54.705573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c860ca7756'
down_revision = 'aed7deaca688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'url')
    # ### end Alembic commands ###
